replicasCount: 1
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/syncer
  tag: latest
  pullPolicy: Always

config: {}

service:
  type: ClusterIP
  externalRpcPort: 5021
  internalRpcPort: 5021

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

secrets:
  sentryDsn: ""
