replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/syncer
  tag: latest
  pullPolicy: Always
  pullSecrets: 
  - name: regcred

serviceAccount:
  name: default

config: {}

service:
  ports:
    grpc: 5021
    http: 5121

resources:
  limits:
   cpu: 300m
   memory: 512Mi
  requests:
   cpu: 300m
   memory: 512Mi

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  host: syncer.dev.videocoinapis.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    kubernetes.io/ingress.class: nginx
  secret: tls-cert-console-syncer

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-uploader"
  vault.hashicorp.com/agent-inject-secret-common: "videocoin/v1/networks/everest-dev/console/common"
  vault.hashicorp.com/agent-inject-secret-config: "videocoin/v1/networks/everest-dev/console/syncer"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/common" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/syncer" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
